blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from . import views

app_name = "blog"

urlpatterns = [
	path('', views.index , name='index'),
    path('<str:insta_username>/', include([

        path('', views.blog_list, name='blog_list'),
        path('new/', views.blog_latest, name='blog_latest'),
        path('<str:slug>/', views.blog_detail, name='blog_detail'),

    ])),

    # path('facebook/', views.facebook, name='facebook_login'),
    # path('profile/', views.profile, name='profile'),

]

insta2blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from accounts.views import (login_view, logout_view, register_view)


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('welcome/', include('newsletter.urls', namespace='newsletter')),
    path('account/', include('accounts.urls', namespace='accounts')),
    

    path('privacy_policy', TemplateView.as_view(template_name='privacy_policy.html') , name='privacy_policy'),
    path('term_of_use', TemplateView.as_view(template_name='term_of_use.html') , name='term_of_use'),

    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),

    path('', include('blog.urls', namespace='blog')),

]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = "newsletter"

from . import views

urlpatterns = [
	path('', views.index , name='index'),
	path('features', views.features , name='features'),
    path('step_1', views.paywall_test , name='paywall_test'),
    path('thankyou', views.thankyou , name='thankyou'),
	path('newsletter_signup', views.newsletter_signup , name='newsletter_signup'),
	path('<str:variable>/step_2/', views.collect_email , name='collect_email'),
]

newsletter/models.py
from django.db import models

# Create your models here.
# Create your models here.
class newsletter_list(models.Model):
	
	THRESHOLD_LIST = (
		('free-version', 'FREE'),
		('paid-15', '15USD'),
		('paid-30', '30USD'),
		)

	email_address 			=			models.EmailField(max_length=254, blank=False, null=False)
	user_name				=			models.CharField(max_length=200, blank=True, null=True)
	threshold				=			models.CharField(max_length=20, choices=THRESHOLD_LIST, default=THRESHOLD_LIST[0][0])
	
	timestamp				=			models.DateTimeField(auto_now=False, auto_now_add=True)
	updated					=			models.DateTimeField(auto_now=True, auto_now_add=False)

	def __str__(self):
		return(self.email_address)

	class Meta:
		ordering	 		=			["-timestamp", "-updated"]
		verbose_name 		= 			"Interested Person"
		verbose_name_plural = 			"Interested People"

newsletter/forms.py
from django import forms
from django.core.validators import validate_email

from .models import newsletter_list

# Form for "newsletter_list"
class NewsletterForm(forms.ModelForm):
    class Meta:
        model = newsletter_list
        fields = [
        'email_address',
        ]

    def clean_contact(self):
        this_email = self.cleaned_data.get('email_address')
        try:
            validate_email(this_email)
        except forms.ValidationError:
            raise forms.ValidationError("Please enter a Valid Email address")

        existing_email = newsletter_list.objects.filter(email_address=this_email)

        if existing_contact:
            print("CONFLICT OF EMAILS")
            raise forms.ValidationError("You already submitted a request with these credentials")
        else:
            print("NO CONFLICT FOUND")
            return this_email

    def __init__(self, *args , **kwargs):
        super(NewsletterForm, self).__init__(*args, **kwargs)
        self.fields["email_address"].help_text = "Please expect our email with in 24 hours."
        self.fields["email_address"].label = "Your Email Addresss"

newsletter/views.py
from django.shortcuts import render, get_object_or_404
from django.http import (
	Http404, HttpResponse, HttpResponsePermanentRedirect, HttpResponseRedirect,
)
from django.urls import reverse
from django.conf import settings

from newsletter.forms import NewsletterForm
from newsletter.models import newsletter_list
# LANDING PAGE
def index(request):
	if request.method == 'POST':
		form = NewsletterForm(request.POST or None)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.threshold = newsletter_list.THRESHOLD_LIST[0][0]
			instance.save()
			return HttpResponseRedirect(reverse('newsletter:thankyou'))
	else:
		form = NewsletterForm()
	context = {
		'form' : form,
		'show_last_div' : False,
		'production' : settings.PRODUCTION,
	}

	return render(request, 'newsletter/landing.html', context)

def thankyou(request):
	context = {
		'show_last_div' : False,
		'production' : settings.PRODUCTION,
	}

	return render(request, 'newsletter/thankyou.html', context)

def features(request):
	
	if request.method == 'POST':
		form = NewsletterForm(request.POST or None)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.threshold = newsletter_list.THRESHOLD_LIST[0][0]
			instance.save()
			return HttpResponseRedirect(reverse('newsletter:thankyou'))
	else:
		form = NewsletterForm()
	context = {
		'form' : form,
		'show_last_div' : False,
		'production' : settings.PRODUCTION,
	}

	return render(request, 'newsletter/features.html', context)

def newsletter_signup(request):
	if request.method == 'POST':
		form = NewsletterForm(request.POST or None)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.threshold = newsletter_list.THRESHOLD_LIST[0][0]
			instance.save()
			return HttpResponseRedirect(reverse('newsletter:thankyou'))
	else:
		form = NewsletterForm()


	context = {
		'form' : form,
		'show_last_div' : False,
		'production' : settings.PRODUCTION,
	}
	return render(request, 'newsletter/newsletter_signup.html', context)

def collect_email(request, variable=None):

	if request.method == 'POST':

		threshold_ = None
		if variable == 'one':
			threshold_ = newsletter_list.THRESHOLD_LIST[0][0]
		elif variable == 'two':
			threshold_ = newsletter_list.THRESHOLD_LIST[1][0]
		elif variable == 'three':
			threshold_ = newsletter_list.THRESHOLD_LIST[2][0]
		else:
			threshold_ = newsletter_list.THRESHOLD_LIST[0][0]

		form = NewsletterForm(request.POST or None)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.threshold = threshold_
			instance.save()
			return HttpResponseRedirect(reverse('newsletter:thankyou'))
	else:
		form = NewsletterForm()


	context = {
		'form' : form,
		'show_last_div' : False,
		'production' : settings.PRODUCTION,
	}
	return render(request, 'newsletter/collect_email.html', context)


def paywall_test(request):
	if request.method == 'POST':
		form = NewsletterForm(request.POST or None)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.threshold = newsletter_list.THRESHOLD_LIST[0][0]
			instance.save()
			return HttpResponseRedirect(reverse('newsletter:thankyou'))
	else:
		form = NewsletterForm()
	context = {
		'form' : form,
		'show_last_div' : False,
		'production' : settings.PRODUCTION,
	}
	return render(request, 'newsletter/paywall_test.html', context)

newsletter/templates/newsletter/collect_email.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Get Updates | {{ block.super }}
{% endblock %}

{% block head_extras %}
{{ form.media }}
{% endblock %}


{% block content_1 %}

<!-- Icons Grid -->
<section class="features-icons bg-light text-center" style="padding-top: 0px;">
	<div class="container">
		<div class="row">
			<div class="col-xl-9 mx-auto">
				<div style="margin-top: 100px"></div>
				<!-- <img class="img-fluid mb-3" width="40%" src="{% static 'base/img/LogoMakr_5MpNGv.png' %}" alt=""> -->
				<!-- <br><span style="font-size: 80px;">Insta<b class="text-primary">2Blog</b></span> -->
				<h1 class="mb-5">Oops..</h1>
			</div>
		</div>
		<div class="row justify-content-md-center">
			<div class="col-lg-8">
				
				<h3 class="text-primary">Looks like you've caught us in Alpha Version.</h3>
				<!-- <p class="lead mb-0">Looks like you've caught us in development mode.</p> -->
				<p>
					I am working hard to bring Insta<b class="text-primary">2Blog</b> to life. The things are in motion.
					<br> Right now you can Register for free.
					<br>
					<br>
					<a class="btn btn-lg btn-outline-primary" href="{% url 'register' %}">Register</a>
					<br><br><hr> If you'd like us to send you a remainder when Insta<b class="text-primary">2Blog</b> Pro is ready, just put your email address below!
				</p>
				<br>
				<!-- Begin Mailchimp Signup Form -->
				<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
				<style type="text/css">#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }</style>
				<div id="mc_embed_signup">
					<form action="https://insta2blog.us19.list-manage.com/subscribe/post?u=c8e00fd0edf4c18dd2f14e792&amp;id=285d883315" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
						<div id="mc_embed_signup_scroll">

							<div class="mc-field-group">
								<label for="mce-EMAIL">Email Address </label>
								<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
							</div>
							<div id="mce-responses" class="clear">
								<div class="response" id="mce-error-response" style="display:none"></div>
								<div class="response" id="mce-success-response" style="display:none"></div>
							</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
							<div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c8e00fd0edf4c18dd2f14e792_285d883315" tabindex="-1" value=""></div>
							<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
						</div>
					</form>
				</div>
				<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
				<!--End mc_embed_signup-->
			</div>
		</div>
	</div>
</section>


{% endblock %}

newsletter/templates/newsletter/features.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Features | {{ block.super }}
{% endblock %}

{% block head_extras %}
{{ form.media }}
{% endblock %}


{% block content_1 %}

<!-- Icons Grid -->
<section class="features-icons bg-light text-center" style="padding-top: 0px;">
	<div class="container">
		<div class="row">
			<div class="col-xl-9 mx-auto">
				<div style="margin-top: 100px"></div>
				<!-- <img class="img-fluid mb-3" width="40%" src="{% static 'base/img/LogoMakr_5MpNGv.png' %}" alt=""> -->
				<!-- <br><span style="font-size: 80px;">Insta<b class="text-primary">2Blog</b></span> -->
				<h1 class="mb-5">Features</h1>
			</div>
		</div>
		<div class="row justify-content-md-center">
			<div class="col-lg-8">
				
				<h3 class="text-primary">First Version</h3>
				<p class="lead mb-0">The first version of this website will be very simple. Every time you post, we will create a blog post for, on our website.<br>For example, if your account on instagram is <span class="text-primary">@<b>AliCoderMaker</b></span>, then your blog posts will be on <span class="text-primary">insta2blog.com/<b>AliCoderMaker</b>.</span></p>
				<br><br>
				<p class="lead mb-0">Custom Markup for the blog will be available for all users.</p>
<br>
<h4>For example:</h4><br>
				<table class="table">
					<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">on Instagram</th>
							<th scope="col">on Blog</th>
							<th scope="col">Explain</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<th scope="row">1</th>
							<td>@alicodermaker</td>
							<td><a target="_blank" href="https://www.instagram.com/alicodermaker">@alicodermaker</a></td>
							<td>Links will automatically be created to send visitor towards instagram.</td>


						</tr>
						<tr>
							<th scope="row">2</th>
							<td>#Blogger</td>
							<td><a target="_blank" href="https://www.instagram.com/explore/tags/blogger/">#Blogger</a></td>
							<td>Each hashtag will be changed to links, directing to said hashtag.</td>

						</tr>
						<tr>
							<th scope="row">3</th>
							<td>For more info, check Link In bio</td>
							<td>For more info, <a target="_blank" href="http://insta2blog.com/?ref=insta2blog">click here</a></td>
							<td>Depending on the link in your Instagram's bio, at the time of posting, this redirect to the link in your bio.</td>
						</tr>
					</tbody>
				</table>
				<!-- <p>Check out our <a href="{% url 'newsletter:paywall_test' %}">Pricing and Plans</a></p> -->
			</div>
		</div>
		<div style="margin-top: 100px"></div>
		<div class="row">
			<div class="col-xl-6">
				<h4>Stay in loop</h4>
				<p>
					To follow the development and updates of Insta2Blog, drop your email address here! I promise I won't spam you.
				</p>
			</div>
			<div class="col-xl-6">				
				<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
					{{ form|crispy }}
					<input type='submit' class='btn btn-outline-primary btn-lg' value='submit'/>
				</form>
			</div>
		</div>
	</div>
</section>


{% endblock %}

newsletter/templates/newsletter/landing.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
{{ block.super }}
{% endblock %}


{% block other_meta %}

<meta name="twitter:card" content="summary_large_image">

<meta name="twitter:site" content="@AliCoderMaker">

<meta name="twitter:creator" content="@AliCoderMaker">

<meta property="og:url" content="{{ request.build_absolute_uri }}">

<meta property="og:image" content="https://s3.amazonaws.com/side-projects/insta2blog/static/base/img/insta2blog-card-1.png">

<meta name="twitter:image" content="https://s3.amazonaws.com/side-projects/insta2blog/static/base/img/insta2blog-card-1.png">

<meta name="twitter:title" content="Drive Traffic to your Instagram, from Google SEO.">

<meta property="og:title" content="Drive Traffic to your Instagram, from Google SEO.">

<meta name="twitter:description" content="Insta2Blog helps you drive traffic from Google Search to your Instagram Posts, by automatically creating a blog everytime you post on Instagram">

<meta property="og:description" content="Insta2Blog helps you drive traffic from Google Search to your Instagram Posts, by automatically creating a blog everytime you post on Instagram">	

{% endblock %}


{% block head_extras %}
{{ form.media }}
{% endblock %}


{% block content_1 %}

<!-- Icons Grid -->
<section class="features-icons bg-light text-center" style="padding-top: 0px;">
	<div class="container">
		<div class="row">
			<div class="col-xl-9 mx-auto">
				<img class="img-fluid mb-3" width="40%" src="{% static 'base/img/LogoMakr_5MpNGv.png' %}" alt="">
				<br><span style="font-size: 80px;">Insta<b class="text-primary">2Blog</b></span>
				<h1 class="mb-5">One click blog from your Instagram.</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4">
				<div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
					<div class="features-icons-icon d-flex">
						<h2 class="m-auto text-primary">1</h2>
					</div>
					<h3>Sign up</h3>
					<p class="lead mb-0">Create an account on Insta<b class="text-primary">2Blog</b>.</p>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
					<div class="features-icons-icon d-flex">
						<h2 class="m-auto text-primary">2</h2>
					</div>
					<h3>Post on Instagram</h3>
					<p class="lead mb-0">Just like a regular day, post on Instagram.</p>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="features-icons-item mx-auto mb-0 mb-lg-3">
					<div class="features-icons-icon d-flex">
						<h2 class="m-auto text-primary">3</h2>
					</div>
					<h3>Relax</h3>
					<p class="lead mb-0">We do the rest and create your blog post. <a href="{% url 'newsletter:features' %}">Learn more</a></p>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col" style="text-align: center;">
				<br>
				<br>
				<br>
				<a href="{% url 'register' %}" class="btn btn-lg btn-outline-primary">
					Start your Free Trial
				</a>	
			</div>
		</div>
	</div>
</section>

<!-- <section class="call-to-action text-white text-center">
	<div class="overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-xl-9 mx-auto">
				<h2 class="mb-4">Interested?</h2>
			</div>
			<div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
				<a href="{% url 'newsletter:paywall_test' %}" class="btn btn-primary btn-lg">Plans and Pricing</a>
			</div>
		</div>
	</div>
</section> -->



<section class="showcase">
	<div class="row">
		<div class="col" style="text-align: center;">
			<div style="margin-top: 100px"></div>
			<!-- <img class="img-fluid mb-3" width="40%" src="{% static 'base/img/LogoMakr_5MpNGv.png' %}" alt=""> -->
			<!-- <br><span style="font-size: 80px;">Insta<b class="text-primary">2Blog</b></span> -->
			<h1 class="mb-5 text-muted">Features</h1>
		</div>
	</div>

	<div class="container-fluid p-0">
		<div class="row no-gutters">
			<div class="col-lg-6 order-lg-2 my-auto showcase-text">
				<h2>"Link In Bio"</h2>
				<p class="lead mb-0">With aim to help with your mission on Instagram, we have implemented a few features. Link for instance, <i>Link in bio</i>. When your write Link in bio in your caption, those text will become a link on the blog, redirecting your visitors to the link, thats in your bio, at the time of posting on instagram.</p>
			</div>
			<div class="col-lg-6 order-lg-1 text-white showcase-img">
				<img src="{% static 'base/img/explained_1.png' %}" class="img-fluid" alt="Responsive image">
			</div>
		</div>
		<div class="row no-gutters">
			<div class="col-lg-6 order-lg-1 my-auto showcase-text">
				<h2>Instagram Hashtags or User Mentions.</h2>
				<p class="lead mb-0">Credit is due where its due.</p>
				<p class="lead mb-0">If you mention a user or Hashtag in your caption, Insta2blog will automatically convert those mentions to links, which upon clicking will redirect your visitor to the mention's page on Instagram.</p>
			</div>
			<div class="col-lg-6 order-lg-2 text-white showcase-img" >
				<img src="{% static 'base/img/explained_2.png' %}" class="img-fluid" alt="Responsive image">
			</div>
		</div>
		<div class="row no-gutters">
			<div class="col-lg-6 order-lg-2 my-auto showcase-text">
				<h2>Customer Support</h2>
				<p class="lead mb-0">Me being an Indie developer, I can always be there for you.<br>Need a few feature? if enough people want it, it can be done. By using this service, you are helping an Indiedev!</p>
			</div>
			<div class="col-lg-6 order-lg-1 text-white showcase-img">
				<img src="{% static 'base/img/bg-showcase-3.jpg' %}" class="img-fluid" alt="Responsive image">
			</div>
		</div>
	</div>
</section>

<!-- Testimonials -->
<section class="testimonials text-center bg-light">
	<div class="container">
		<h2 class="mb-5 text-muted">What people are saying...</h2>
		<div class="row">
			<div class="col-lg-4">
				<div class="testimonial-item mx-auto mb-5 mb-lg-0">
					<img class="img-fluid rounded-circle mb-3" src="{% static 'base/img/omgshecodes.jpg' %}" alt="">
					<h5><a target='_blank' href="https://www.instagram.com/omgshecodes/">Yas <br><small>omgshecodes</small></a></h5>
					<p class="font-weight-light mb-0">"I need this real bad"</p>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="testimonial-item mx-auto mb-5 mb-lg-0">
					<img class="img-fluid rounded-circle mb-3" src="{% static 'base/img/testimonials-2.jpg' %}" alt="">
					<h5><a target='_blank' href="https://www.instagram.com/edouard_iosdev/">Edouard<br><small>edouard_iosdev</small></a></h5>
					<p class="font-weight-light mb-0">"Lots of potential, looking forward to see this brought to life"</p>
				</div>
			</div>
			<!-- <div class="col-lg-4">
				<div class="testimonial-item mx-auto mb-5 mb-lg-0">
					<img class="img-fluid rounded-circle mb-3" src="{% static 'base/img/testimonials-3.jpg' %}" alt="">
					<h5>Sarah	W.</h5>
					<p class="font-weight-light mb-0">"Thanks so much for making these free resources available to us!"</p>
				</div>
			</div> -->
		</div>
	</div>
</section>


<section class="features-icons bg-light text-center" style="padding-top: 0px;">
	<div class="container">
		<div class="row">
			<div class="col-xl-9 mx-auto">
				<div style="margin-top: 100px"></div>
				<!-- <img class="img-fluid mb-3" width="40%" src="{% static 'base/img/LogoMakr_5MpNGv.png' %}" alt=""> -->
				<!-- <br><span style="font-size: 80px;">Insta<b class="text-primary">2Blog</b></span> -->
				<h1 class="mb-5 text-muted">Pricing</h1>
			</div>
		</div>
		{% include 'newsletter/paywall_snippet.html' %}
		<div style="margin-top: 100px"></div>
		<!-- Call to Action -->

		<div class="row">
			<div class="col-xl-6">
				<h4>Stay in loop</h4>
				<p>
					To follow the development and updates of Insta2Blog, drop your email address here! I promise I won't spam you.
				</p>
			</div>
			<div class="col-xl-6">				
				<!-- <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
					{{ form|crispy }}
					<input type='submit' class='btn btn-outline-primary btn-lg' value='submit'/>
				</form> -->
				<!-- Begin Mailchimp Signup Form -->
				<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
				<style type="text/css">#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }</style>
				<div id="mc_embed_signup">
					<form action="https://insta2blog.us19.list-manage.com/subscribe/post?u=c8e00fd0edf4c18dd2f14e792&amp;id=285d883315" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
						<div id="mc_embed_signup_scroll">

							<div class="mc-field-group">
								<label for="mce-EMAIL">Email Address </label>
								<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
							</div>
							<div id="mce-responses" class="clear">
								<div class="response" id="mce-error-response" style="display:none"></div>
								<div class="response" id="mce-success-response" style="display:none"></div>
							</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
							<div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c8e00fd0edf4c18dd2f14e792_285d883315" tabindex="-1" value=""></div>
							<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
						</div>
					</form>
				</div>
				<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
				<!--End mc_embed_signup-->
			</div>
		</div>
	</div>
</section>

<!-- Thinks for visiting our page -->
{% endblock %}

newsletter/templates/newsletter/paywall_snippet.html
<div class="row">
	<div class="col-lg-4">
		<div class="features-icons-item mx-auto mb-5 mb-lg-3">
			<div class="features-icons-icon d-flex">
				<h2 class="m-auto text-primary">FREE</h2>
			</div>
			<h3>1 Post per day</h3>
			<p class="lead">One Instagram Business Account</p>
			<ul style="text-align: left;">
				<li>link in bio</li>
				<li>Hashtag Mention</li>
				<li>Username Mention</li>
				<li>Standard Support</li>
			</ul>
			<a href="{% url 'register' %}" class="btn btn-primary">Signup For Free</a>
			<!-- <p class="lead mb-0"></p> -->
		</div>
	</div>
	<div class="col-lg-4">
		<div class="features-icons-item mx-auto mb-5 mb-lg-3">
			<div class="features-icons-icon d-flex">
				<h2 class="m-auto text-primary">$7 Monthly</h2>
			</div>
			<h3>Unlimited posts per day</h3>
			<p class="lead">One Instagram Business Account</p>
			<ul style="text-align: left;">
				<li>link in bio</li>
				<li>Hashtag Mention</li>
				<li>Username Mention</li>
				<li>Dedicated support</li>
			</ul>
			<a href="{% url 'newsletter:collect_email' 'two' %}" class="btn btn-outline-primary">Signup</a>

			<!-- <p class="lead mb-0">Just like a regular day, post on Instagram.</p> -->
		</div>
	</div>
	<div class="col-lg-4">
		<div class="features-icons-item mx-auto mb-0 mb-lg-3">
			<div class="features-icons-icon d-flex">
				<h2 class="m-auto text-primary">$30 Monthly</h2>
			</div>
			<h3>Unlimited posts per day</h3>
			<p class="lead">upto 5 Instagram Business Accounts</p>
			<ul style="text-align: left;">
				<li>link in bio</li>
				<li>Hashtag Mention</li>
				<li>Username Mention</li>
				<li>Dedicated and Prioritised support</li>
			</ul>
			<a href="{% url 'newsletter:collect_email' 'three' %}" class="btn btn-outline-primary">Signup</a>

			<!-- <p class="lead mb-0">We do the rest and create your blog post.</p> -->
		</div>
	</div>
</div>