accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from . import views

app_name = "accounts"

urlpatterns = [
    path('profile/', views.profile, name='profile'),

    # STEP 1 : click on facebook icon to login
    path('facebook/', views.facebook_login, name='facebook_login'),
	
    # STEP 2 : 
    path('facebook_login_view/', views.facebook_login_view, name='facebook_login_view'),	
    
    # STEP 3 : Auto redirected
    path('facebook_get_code/', views.facebook_get_code, name='facebook_get_code'),
	
    # STEP 4 : 
    path('facebook_pages/', views.facebook_pages, name='facebook_pages'),
    
    # STEP 5 : The profile page
    path('insta_account_setup/<int:insta_id>/<str:user_access_token_>/', views.insta_account_setup, name='insta_account_setup'),
    
    # Step 6 : add 10 blog posts
    path('facebook_page_profile/<int:insta_id>/<str:user_access_token_>/', views.facebook_page_profile, name='facebook_page_profile'),
    
    # STEP 7 : The profile page
    path('profile/<str:insta_username>/', views.blog_profile, name='blog_profile'),    
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from . import views

app_name = "blog"

urlpatterns = [
	path('', views.index , name='index'),
    path('<str:insta_username>/', include([

        path('', views.blog_list, name='blog_list'),
        path('new/', views.blog_latest, name='blog_latest'),
        path('<str:slug>/', views.blog_detail, name='blog_detail'),

    ])),

    # path('facebook/', views.facebook, name='facebook_login'),
    # path('profile/', views.profile, name='profile'),

]

insta2blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from accounts.views import (login_view, logout_view, register_view)


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('welcome/', include('newsletter.urls', namespace='newsletter')),
    path('account/', include('accounts.urls', namespace='accounts')),
    

    path('privacy_policy', TemplateView.as_view(template_name='privacy_policy.html') , name='privacy_policy'),
    path('term_of_use', TemplateView.as_view(template_name='term_of_use.html') , name='term_of_use'),

    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),

    path('', include('blog.urls', namespace='blog')),

]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class insta_account(models.Model):
	# a paid user can have up to 5 instagram accounts connected. This is where we store insta bio, user, 
	# insta_id, 
	user 					=			models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
	insta_id				=			models.CharField(max_length=30, blank=False, null=False, default="")
	insta_username			=			models.CharField(max_length=30, blank=False, null=False, default="")
	bio						=			models.TextField(max_length=150, blank=True, null=True, default="user bio here")

	# add a field to enable user's custom bio, or load directly from Instagram. A simple boolean field should suffice.
	timestamp				=			models.DateTimeField(auto_now=False, auto_now_add=True)
	updated					=			models.DateTimeField(auto_now=True, auto_now_add=False)
	def __str__(self):
		return(self.insta_username)

accounts/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import PasswordChangeForm
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponse, Http404

from django.contrib.auth import (
	authenticate,
	get_user_model,
	login,
	logout,
	update_session_auth_hash
)
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404

from .forms import UserLoginForm, UserRegisterForm, InstaIDForm, NewInstaAccount
from .models import insta_account
from blog.models import blog
import os
import requests
import facebook
from facebook import GraphAPI


#  I M P O R T A N T
# app_id and app_secret must be variables from env... its not save to have them hardcoded here.	
# These keys and values can be found in ../bin/activate

app_id = os.environ.get('FACEBOOK_APP_ID')
app_secret = os.environ.get('FACEBOOK_APP_SECRET')
PERMS_LIST = ["manage_pages","instagram_basic", "publish_pages", "pages_show_list"]

REDIRECT_BASE = 'https://localhost:8000/account/'

# graph = facebook.GraphAPI()
USER_ACCESS_TOKEN = ''

def login_view(request):
	if request.user.is_authenticated:
		return HttpResponseRedirect(reverse('accounts:profile'))
	next = ""

	if request.GET:  
		next = request.GET['next']

	dbug = settings.DEBUG
	form = UserLoginForm(request.POST or None)
	if form.is_valid():
		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")
		user = authenticate(username=username, password=password)
		login(request,user)
		if next == "":
			# return HttpResponseRedirect("/")
			return HttpResponseRedirect(reverse('blog:index'))
		else:
			return HttpResponseRedirect(next)

	context = {
		"name_nav" : 'login',
		"nbar" : "login",
		"form" : form,
		"dbug" : dbug,
		'top_text' : 'Login',
		'form_text' : 'details',
		'tab_text' : 'Submit',
		'page' : 'full-page',
		'production' : settings.PRODUCTION,

	}
	return render(request, 'accounts/login.html', context)

# STEP 1
def register_view(request):
	if request.user.is_authenticated:
		return HttpResponseRedirect(reverse('blog:index'))
	next = ""

	if request.GET:
		next = request.GET['next']

	dbug = settings.DEBUG
	form = UserRegisterForm(request.POST or None)
	if form.is_valid():
		user = form.save(commit=False)
		password = form.cleaned_data.get("password")
		user.set_password(password)
		user.save()
		new_user = authenticate(username=user.username, password=password)

		login(request, new_user)
		# change redirect to edit bio page
		# return HttpResponseRedirect("/")
		return HttpResponseRedirect(reverse('accounts:facebook_login_view'))
	context = {
		"name_nav" : 'register',	
		"nbar" : "register",
		"form" : form,
		'dbug' : dbug,
		'top_text' : 'Register',
		'form_text' : 'details',
		'tab_text' : 'Submit',
		'page' : 'full-page',
		'production' : settings.PRODUCTION,

	}
	return render(request, 'accounts/login.html', context)


'''
	F A C E B O O K    A P P    P L A N

	1. click on Register, SIGN UP ON WEBSITE
	2. take user to Connect With Facebook (CWF)
	3. ON CWF, click button
		take user to facebook_01():
			simple button which reditect to facebook login.
			GraphAPI().get_auth_url
		redirect to facebook_02():
			Show all Facebook Pages
	3. Allow user to select a facebook page.
		Get the connected_instagram_account id
	4. using Instagram ID, fetch past 10 posts, and make them to blog


	PAGE 1
			register_view()
			Register on Insta2Blog

	PAGE 2
			facebook_login()
			Register via facebook,
			
			OPENS NEW TAB, AUTHORISE VIA FACEBOOK

	PAGE 3
			From Code/token, get the access_token
			ask user to pleaase wait. this will auto redirect to another page soon.

	PAGE 4
			TBD facebook_pages()
			List of all Pages.
			Click on one Page Link, to connect via Facebook.

	PAGE 5
			profile()
			Profile Page
'''

# ALTERNATIVE - STEP 2 PRETTY MUCH USELESS AT THIS MOMENT
@login_required
def facebook_login(request):
	# detect if user is logged in or not
	
	context = {
		'top_text' : 'Login to facebook',
		'form_text' : 'For accessing to instagram account, we need to login via your facebook, if you are already logged in, click "Continue"',
		'production' : settings.PRODUCTION,
		'tab_text' : 'Submit',

	}
	return render(request, 'accounts/facebook_login.html', context)

# STEP 2
@login_required
def facebook_login_view(request):
	# Check is user is online, connected to facebook.
	# if facebook is connected, send to facebook_login_view.
	# else, show facebook_login

	# This will get the link to login to the facebook app.
	facebook_login_url = get_user_access_token()
	context = {
		'production' : settings.PRODUCTION,
		'tab_text' : 'Continue',
		'facebook_login_url' : facebook_login_url,

	}
	return render(request, 'accounts/facebook_login_view.html', context)

# After this the user will be redirected to a page where he will just wait and see a few redirects.
# STEP 3
@login_required
def facebook_get_code(request):

	#  This is a part of a series of redirects.
	"""
		This page will return either 'code' or 'token'


		1.	When 'code' is received, it has to be exchanged for an access token using an endpoint. The call will need to be server-to-server, since it involves your app secret. (Your app secret should never end up in client code.)
		2.	When 'token' is received, it needs to be verified. You should make an API call to an inspection endpoint that will indicate who the token was generated for and by which app. As this API call requires using an app access token, never make this call from a client. Instead make this call from a server where you can securely store your app secret.
		3.	When 'code' and 'token' are both received, both steps should be performed.
		
		Exchanging Code for an Access Token
		use GraphAPI().get_access_token_from_code()
	"""
	get_code = request.GET.get('code', '')
	get_token = request.GET.get('token', '')
	
	if get_code:
		code = get_code
		user_access_token_ = get_access_token_code(code, 'facebook_get_code')
		# using session to send data between two views. this is how you send data, 
		request.session['user_access_token_'] = user_access_token_
		# and this is how you retrieve it
		# user_access_token_ = request.session.get('user_access_token_')
		return HttpResponseRedirect(reverse('accounts:facebook_pages'))

	context = {
		'top_text' : 'Please wait',
		'form_text' : 'We are working on it',
		'production' : settings.PRODUCTION,

	}
	return render(request, 'accounts/facebook_pages.html', context)

# STEP 4
@login_required
def facebook_pages(request):
	# this page should show all the pages in user's account.
	user_access_token_ = request.session.get('user_access_token_')

	graph = facebook.GraphAPI(access_token=user_access_token_ , version="3.2")
	# get_all_connections param will get anything you need. 
	# First verify it on https://developers.facebook.com/tools/explorer/, and then convert that URL to this 
	# fetch statement.
	# keep in mind, everythind after "me" should come in "fields". thats going through *args
	all_pages = graph.get_all_connections(id='me', connection_name='accounts', fields='access_token,name,instagram_business_account{username,name,media_count,profile_picture_url,followers_count,follows_count,id}')

	"""
	now i need to stop use from registering with the same account multiple times.
	Therefore now here we will fetch all the accounts created by use and disable the button to
	accounts the user has already registered
	"""

	# fetch all the accounts by request.user

	current_accounts = insta_account.objects.filter(user=request.user)

	# for page in all_pages:
	# 	if page.instagram_business_account.name in current_accounts:
	# 		print("registered")
	# 	else:
	# 		print("New Account")
	context = {
		'all_pages' : all_pages,

		'current_accounts' : current_accounts,
		'production' : settings.PRODUCTION,
		'top_text' : 'Select Facebook Page',
		'form_text' : 'Please Select the facebook Page which is connected to the Instagram Account you wish to Use.',
	}
	return render(request, 'accounts/facebook_pages.html', context)

@login_required
def insta_account_setup(request, insta_id=None, user_access_token_=None):

	graph = facebook.GraphAPI(access_token=user_access_token_ , version="3.2")
		
	"""
		create an insta_account for this user.
		CHECK THESE FIRST
			1. how many accounts does user already has
				* if free user, they can have only one account
				* if $7 customer, they can have only one account
				* if $30 user, they can have a max of 5 accounts
				* A N Y W A Y S, if user is requesting, for more accounts, take them to payment page and ask them
				to wait for me to write the code.
			2. fetch the data required
				* bio
				* username, set it to user's insta_username

				A D D I T I O N A L    D A T A,
					Since I will be using the 'graph' again, I may have to use the new access tokens. these can be obtained from previous step.

						graph = facebook.GraphAPI(access_token=user_access_token_ , version="3.2")
						user_data = graph.get_all_connections(id='me', connection_name='media', fields='limit{10},caption')
	"""	
	bio = graph.get_object(id=insta_id, fields='biography,username')
	# user, insta_id, insta_username, bio,

	try:
		check_duplicate = insta_account.objects.get(insta_id=insta_id)

		messages.warning(request, "The Account  ({}) is already registered".format(bio['username']))
		return HttpResponseRedirect(reverse('accounts:facebook_pages'))

	except insta_account.DoesNotExist:
		pass


	try:
		user_bio = bio['biography']
	except Exception as e:
		user_bio = "Hey, We are Using Insta2blog to make this blog!"

	form = NewInstaAccount(request.POST or None)
	if form.is_valid():
		print('form is valid')
	else:
		print('form is not valid')
		instance = form.save(commit=False)
		instance.user = request.user
		instance.bio = user_bio
		instance.insta_id = insta_id
		instance.insta_username = bio['username']

accounts/templates/accounts/blog_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
{{request.user.username}}'s Profile | {{ block.super }}
{% endblock %}

{% block head_extras %}{% endblock %}

{% block content_2 %}
<div class="row">
	<div class="col">
		<h3>Welcome {{request.user.username}}</h3>
		<h3><small>{{profile}}</small></h3>
	</div>
</div>
<div class="row">
	<div class="col">
		<div style="margin-top: 50px"></div>
		<h4 class="text-muted">
			<i class="fas fa-cogs"></i> Settings
		</h4>

		<table class="table">
			<tr style="border: none;">
				<th style="border: none;">Settings</th>
				<td style="border: none;"><p class="text-muted">Coming soon</p></td>
			</tr>
			<tr style="border: none;">
				<th style="border: none;">Fetch New Post</th>
				<td style="border: none;"><p class="text-muted">Coming soon</p></td>
			</tr>
			<tr style="border: none;">
				<th style="border: none;">Change Bio</th>
				<td style="border: none;"><p class="text-muted">Coming soon</p></td>
			</tr>
		</table>
	</div>
</div>

<div class="row">
	<div class="col">
		<div style="margin-top: 50px"></div>
		<h4 class="float-right"><a href=""><i class="fas fa-plus-square"></i> Add</a></h4>
		<h4 class="text-muted">
			<i class="fas fa-th-list"></i> List of all blogs
		</h4>
		<table class="table">
			<thead>
				<th>Blog Title</th>
				<td>View</td>
				<td>Edit</td>
				<td>Delete</td>
				<td>Draft</td>
			</thead>
			{% for blog in blog_posts %}
			<tr>
				<th>{{blog.blog_title}}</th>
				<td><a href="{% url 'blog:blog_detail' profile.insta_username blog.blog_slug %}"><i class="fas fa-eye"></i></a></td>
				<td><a href=""><i class="fas fa-edit"></i></a></td>
				<td><a href=""><i class="fas fa-trash-alt"></i></a></td>
				<td><a href=""><i class="fas fa-eye-slash"></i></a></td>
			</tr>
			{% empty %}
			<tr>
				<td colspan="5" style="text-align: center;"><h5 class="text-muted">Looks like you dont have any blogs post yet.</h5></td>
			</tr>
			{% endfor %}
		</table>
		<hr>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/facebook_login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
{{top_text}} | {{ block.super }}
{% endblock %}

{% block head_extras_body %}
<script>
	console.log('fbAsyncInit')
	window.fbAsyncInit = function() {
		FB.init({
			appId      : '510918386043485',
			cookie     : true,
			xfbml      : true,
			version    : 'v3.2'
		});


		FB.AppEvents.logPageView();
		FB.getLoginStatus(function(response) {
			statusChangeCallback(response);
		});
	    $(document).trigger('fbload');  //  <---- THIS RIGHT HERE TRIGGERS A CUSTOM EVENT CALLED 'fbload'
		
	};
	(function(d, s, id){
		console.log('function d s id')
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) {return;}
		js = d.createElement(s); js.id = id;
		js.src = "https://connect.facebook.net/en_US/sdk.js";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
	
    console.log("opening page 1!");
	
    // 'fbload',  //  <---- HERE'S OUR CUSTOM EVENT BEING LISTENED FOR

	FB.getLoginStatus(function(response) {
		if (response.status === 'connected') {
			var accessToken = response.authResponse.accessToken;
		} 
	} );
    console.log("opening page 2!");

	FB.getLoginStatus(function(response) {
		if (response.status === 'connected') {
    // The user is logged in and has authenticated your
    // app, and response.authResponse supplies
    // the user's ID, a valid access token, a signed
    // request, and the time the access token 
    // and signed request each expire.
    var uid = response.authResponse.userID;
    var accessToken = response.authResponse.accessToken;
    console.log(accessToken)
	alert(accessToken);
    console.log("connected!");

} 
    else if (response.status === 'authorization_expired') {
    // The user has signed into your application with
    // Facebook Login but must go through the login flow
    // again to renew data authorization. You might remind
    // the user they've used Facebook, or hide other options
    // to avoid duplicate account creation, but you should
    // collect a user gesture (e.g. click/touch) to launch the
    // login dialog so popup blocking is not triggered.
    console.log("authorization_expired!");
    var nnn = "dd"}
    else if (response.status === 'not_authorized') {
    // The user hasn't authorized your application.  They
    // must click the Login button, or you must call FB.login
    // in response to a user gesture, to launch a login dialog.
    console.log("not_authorized!");
    var nnn = "dd"}
    else {
    	console.log("Not_logged_in!");

    // The user isn't logged in to Facebook. You can launch a
    // login dialog with a user gesture, but the user may have
    // to log in to Facebook before authorizing your application.
}
});	
</script>

{% endblock %}

{% block content_2 %}
<div class="row">
	<div class="col">
		<h3>{{top_text}}</h3>
		<h3><small>{{form_text}}</small></h3>
	</div>
</div>
<div class="row">
	<div class="col">
		
		<div class="fb-login-button" data-max-rows="1" data-size="large" data-button-type="continue_with" data-show-faces="false" data-auto-logout-link="true" data-use-continue-as="true"></div>
		<br>
		<br>
		
	</div>
</div>
{% endblock %}

accounts/templates/accounts/facebook_login_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
{{top_text}} | {{ block.super }}
{% endblock %}

{% block head_extras_body %}
<!-- <script>
	console.log('fbAsyncInit')
	window.fbAsyncInit = function() {
		FB.init({
			appId      : '510918386043485',
			cookie     : true,
			xfbml      : true,
			version    : 'v3.2'
		});


		FB.AppEvents.logPageView();
		FB.getLoginStatus(function(response) {
			statusChangeCallback(response);
		});
	    $(document).trigger('fbload');  //  <---- THIS RIGHT HERE TRIGGERS A CUSTOM EVENT CALLED 'fbload'
		
	};
	(function(d, s, id){
		console.log('function d s id')
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) {return;}
		js = d.createElement(s); js.id = id;
		js.src = "https://connect.facebook.net/en_US/sdk.js";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
	
    console.log("opening page 1!");
	
    // 'fbload',  //  <---- HERE'S OUR CUSTOM EVENT BEING LISTENED FOR

	FB.getLoginStatus(function(response) {
		if (response.status === 'connected') {
			var accessToken = response.authResponse.accessToken;
		} 
	} );
    console.log("opening page 2!");

// 	FB.getLoginStatus(function(response) {
// 		if (response.status === 'connected') {
//     // The user is logged in and has authenticated your
//     // app, and response.authResponse supplies
//     // the user's ID, a valid access token, a signed
//     // request, and the time the access token 
//     // and signed request each expire.
//     var uid = response.authResponse.userID;
//     var accessToken = response.authResponse.accessToken;
//     console.log(accessToken)
// 	alert(accessToken);
//     console.log("connected!");

// } 
//     else if (response.status === 'authorization_expired') {
//     // The user has signed into your application with
//     // Facebook Login but must go through the login flow
//     // again to renew data authorization. You might remind
//     // the user they've used Facebook, or hide other options
//     // to avoid duplicate account creation, but you should
//     // collect a user gesture (e.g. click/touch) to launch the
//     // login dialog so popup blocking is not triggered.
//     console.log("authorization_expired!");
//     var nnn = "dd"}
//     else if (response.status === 'not_authorized') {
//     // The user hasn't authorized your application.  They
//     // must click the Login button, or you must call FB.login
//     // in response to a user gesture, to launch a login dialog.
//     console.log("not_authorized!");
//     var nnn = "dd"}
//     else {
//     	console.log("Not_logged_in!");

//     // The user isn't logged in to Facebook. You can launch a
//     // login dialog with a user gesture, but the user may have
//     // to log in to Facebook before authorizing your application.
// }
// });	
</script>
 -->
{% endblock %}

{% block content_2 %}
<div class="row">
	<div class="col">
		<h3>Continue With Facebook</h3>
		<h3><small>For Insta2Blog to access your Instagram data, we need to login via your Facebook Account. Please click "Continue" to select an Facebook Page</small></h3>
	</div>
</div>
<div class="row">
	<div class="col">
		<a href="{{ facebook_login_url }}" class='btn btn-outline-primary btn-lg'><i class="fab fa-facebook-square"></i>&nbsp;&nbsp;Continue</a>
		<br>
		<br>
		<hr>
		<h3>Need help?</h3>
		<p>Please read this How to get started guide, to learn how to start using Insta2blog.</p>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/facebook_page_profile.html
facebook_page_profile.html

accounts/templates/accounts/facebook_pages.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
{{top_text}} | {{ block.super }}
{% endblock %}

{% block head_extras_body %}
<!-- <script>
	console.log('fbAsyncInit')
	window.fbAsyncInit = function() {
		FB.init({
			appId      : '510918386043485',
			cookie     : true,
			xfbml      : true,
			version    : 'v3.2'
		});


		FB.AppEvents.logPageView();
		FB.getLoginStatus(function(response) {
			statusChangeCallback(response);
		});
	};
</script>
-->
{% endblock %}

{% block content_2 %}
<div class="row">
	<div class="col">
		<h3>{{top_text}}</h3>
		<h3><small>{{form_text}}</small></h3>
	</div>
</div>
<br>
<br>
<br>
<div class="row">
	<div class="col">
		<div class="card-columns">
			{% for pages in all_pages %}
			{% if pages.instagram_business_account %}
			<div class="card border-primary">
				<div class="card-body text-center">
					<h5 class="card-title text-muted">{{ pages.name }}</h5>
					<p><small><i class="fas fa-check"></i> Instagram Business Account Connected</small></p>
					<hr>
					<img src="{{pages.instagram_business_account.profile_picture_url}}" height="112" width="112" style="margin: 10px; padding: 10px">

					<h6 class="card-subtitle mb-2 text-muted">{{pages.instagram_business_account.name}}
						<br>
						<small>
							<a target="_blank" href="https://instagram.com/{{pages.instagram_business_account.username}}"> {{pages.instagram_business_account.username}}
							</a>
						</small>
					</h6>
					<div class="row">
						<div class="col-4">
							<p>
								{{pages.instagram_business_account.media_count}}
								<br>
								<small>
									Posts
								</small>
							</p>
						</div>
						<div class="col-4">
							<p>
								{{pages.instagram_business_account.followers_count}}
								<br>
								<small>
									Followers
								</small>
							</p>
						</div>
						<div class="col-4">
							<p>
								{{pages.instagram_business_account.follows_count}}
								<br>
								<small>
									Follows
								</small>
							</p>
						</div>
					</div>
					<a href="{% url 'accounts:insta_account_setup' insta_id=pages.instagram_business_account.id user_access_token_=pages.access_token %}" class="btn btn-sm btn-outline-primary">
						Connect with this
					</a>
				</div>
			</div>
			{% else %}
			<div class="card border-dark">
				<div class="card-body text-center">
					<h5 class="card-title text-muted">{{ pages.name }}</h5>
					<p><small>Instagram Business Account Not Connected</small></p>
					<hr>
				</div>
			</div>
			{% endif %}

			{% endfor %}

		</div>
	</div>
</div>
<br>
<br>
<br>
<div class="row">
	<div class="col">
		<h4 class="text-muted">Cant find your Instagram Account?</h4>
		<a href="">Learn how to setup your account on Facebook and Instagram.</a>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/insta_account_setup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
{{top_text}} | {{ block.super }}
{% endblock %}

{% block head_extras_body %}
{% endblock %}

{% block content_2 %}
<div class="row">
	<div class="col">
		<h3>{{top_text}}</h3>
		<h3><small>{{form_text}}</small></h3>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
{{top_text}} | {{ block.super }}
{% endblock %}

{% block header_0 %}
{{ form.media }}
{% endblock %}

{% block content_2 %}
<div class="row">
	<div class="col">
		<h3>{{top_text}}</h3>
		<h3><small>{{form_text}}</small></h3>
	</div>
</div>
<div class="row">
	<div class="col">
		<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
			{{ form|crispy }}
			<input type='submit' class='btn btn-outline-primary btn-lg' value='{{ tab_text }}'/>
		</form>
	</div>
</div>

<!-- login via facebook -->
<!-- <a href="{% url 'accounts:facebook_login' %}">login via Facebook</a>
 -->
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
{{request.user.username}}'s Profile | {{ block.super }}
{% endblock %}

{% block head_extras %}{% endblock %}

{% block content_2 %}
<div class="row">
	<div class="col">
		<h3>Welcome {{request.user.username}}</h3>
		<h3 class="float-right"><a class="btn btn-sm btn-outline-danger" href="{% url 'accounts:facebook_login_view' %}"><i class="far fa-plus"></i> Add More</a></small></h3>

		<h3><small>You have {{accounts|length}} blog accounts</small></h3>
	</div>
</div>
<div class="row">
	<div class="col">
		{% if accounts|length < 1 %}
		<p>Looks like you dont have any Instagram accounts connected.</p>
		<a href="{% url 'accounts:facebook_login_view' %}">Click here to Start Process</a>
		{% else %}
		<div class="card-columns">
			
			{% for account in accounts %}
			<div class="card">
				<div class="card-body">
					<a class="float-right" href=""><i class="fas fa-plus-square"></i> Update</a>
					<h5 class="card-title">{{account.insta_username}}</h5>
					<!-- <h6 class="card-subtitle mb-2 text-muted">{{account}}</h6> -->
					<p class="card-text">{{account.bio|linebreaksbr}}</p>
					<a href="/{{account.insta_username}}" class="card-link">Blog</a>
					<a href="{% url 'accounts:blog_profile' account.insta_username %}" class="card-link">Settings</a>
					<a href="https://instagram.com/{{account.insta_username}}" target="_blank" class="card-link"><i class="fab fa-instagram"></i></a>
				</div>
				<div class="card-footer">
					<a href="{% url 'accounts:blog_profile' account.insta_username %}" class="card-link"><i class="fas fa-tachometer-alt"></i> Dashboard</a><br>
				</div>

			</div>
			{% endfor %}
		</div>

		{% endif %}
	</div>
</div>
{% endblock %}