accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from . import views

app_name = "accounts"

urlpatterns = [
    path('profile/', views.profile, name='profile'),

    # STEP 1 : click on facebook icon to login
    path('facebook/', views.facebook_login, name='facebook_login'),
	
    # STEP 2 : 
    path('facebook_login_view/', views.facebook_login_view, name='facebook_login_view'),	
    
    # STEP 3 : Auto redirected
    path('facebook_get_code/', views.facebook_get_code, name='facebook_get_code'),
	
    # STEP 4 : 
    path('facebook_pages/', views.facebook_pages, name='facebook_pages'),
    
    # STEP 5 : The profile page
    path('insta_account_setup/<int:insta_id>/<str:user_access_token_>/', views.insta_account_setup, name='insta_account_setup'),
    
    # Step 6 : add 10 blog posts
    path('facebook_page_profile/<int:insta_id>/<str:user_access_token_>/', views.facebook_page_profile, name='facebook_page_profile'),
    
    # STEP 7 : The profile page
    path('profile/<str:insta_username>/', views.blog_profile, name='blog_profile'),    
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from . import views

app_name = "blog"

urlpatterns = [
	path('', views.index , name='index'),
    path('<str:insta_username>/', include([

        path('', views.blog_list, name='blog_list'),
        path('new/', views.blog_latest, name='blog_latest'),
        path('<str:slug>/', views.blog_detail, name='blog_detail'),

    ])),

    # path('facebook/', views.facebook, name='facebook_login'),
    # path('profile/', views.profile, name='profile'),

]

insta2blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from accounts.views import (login_view, logout_view, register_view)


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('welcome/', include('newsletter.urls', namespace='newsletter')),
    path('account/', include('accounts.urls', namespace='accounts')),
    

    path('privacy_policy', TemplateView.as_view(template_name='privacy_policy.html') , name='privacy_policy'),
    path('term_of_use', TemplateView.as_view(template_name='term_of_use.html') , name='term_of_use'),

    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),

    path('', include('blog.urls', namespace='blog')),

]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = "newsletter"

from . import views

urlpatterns = [
	path('', views.index , name='index'),
	path('features', views.features , name='features'),
    path('step_1', views.paywall_test , name='paywall_test'),
    path('thankyou', views.thankyou , name='thankyou'),
	path('newsletter_signup', views.newsletter_signup , name='newsletter_signup'),
	path('<str:variable>/step_2/', views.collect_email , name='collect_email'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Insta2Blog | One click blog from your Instagram">
	<meta name="author" content="Ali Khundmiri">
	<title>{% block title %}Insta2Blog | One click blog from your Instagram{% endblock %}</title> <!-- MAX 70 Chars-->
	{% block other_meta %}{% endblock %}


	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'base/apple-touch-icon.png' %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'base/favicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'base/favicon-16x16.png' %}">
	<link rel="manifest" href="{% static 'base/site.webmanifest' %}">
	<link rel="mask-icon" href="{% static 'base/safari-pinned-tab.svg' %}" color="#5bbad5">
	<meta name="msapplication-TileColor" content="#da532c">
	<meta name="theme-color" content="#ffffff">

	<!-- Bootstrap core CSS -->
	<link href="{% static 'base/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

	<!-- Custom fonts for this template -->
	<link href="{% static 'base/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
	<link href="{% static 'base/vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

	<!-- Custom styles for this template -->
	<link href="{% static 'base/css/landing-page.min.css' %}" rel="stylesheet">
	{% block head_extras %}{% endblock %}
	{% if production %}<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-129095159-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-129095159-1');
	</script>{% endif %}
</head>

<body>

	{% if request.user.is_authenticated %}
	<!-- This script is for Facebook login. This is nesessary to use Instagram account, since the launch of new Facebook Graph Instagram API-->

<!-- 
NOTE FROM FACEBOOK DOCUMENTS
The Facebook SDK for JavaScript doesn't have any standalone files that need to be downloaded or installed, instead you simply need to include a short piece of regular JavaScript in your HTML that will asynchronously load the SDK into your pages. The async load means that it does not block loading other elements of your page.
The following snippet of code will give the basic version of the Facebook SDK for JavaScript where the options are set to their most common defaults. Insert the following code snippet directly after the opening <body> tag on each page you want to use Facebook Analytics. Replace {your-app-id} with the App ID and {api-version} with the version of the API you are targeting. The current version isv3.2.
-->
<!-- <script>
	console.log('fbAsyncInit')
	window.fbAsyncInit = function() {
		FB.init({
			appId      : '510918386043485',
			cookie     : true,
			xfbml      : true,
			version    : 'v3.2'
		});


		FB.AppEvents.logPageView();
		FB.getLoginStatus(function(response) {
			statusChangeCallback(response);
		});
	    $(document).trigger('fbload');  //  <---- THIS RIGHT HERE TRIGGERS A CUSTOM EVENT CALLED 'fbload'
		
	};
	(function(d, s, id){
		console.log('function d s id')
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) {return;}
		js = d.createElement(s); js.id = id;
		js.src = "https://connect.facebook.net/en_US/sdk.js";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
</script> -->


{% block head_extras_body %}
{% endblock %}

{% endif %}
<!-- Navigation -->




{% include 'navbar.html' %}
{% if messages %}
{% for message in messages %}
<!-- <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li> -->
<div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
	{{ message }}
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
{% endfor %}
{% endif %}
{% block content_1 %}
{% endblock %}

<div class="container">
	<div class="row">
		<div class="col-lg-2 col-md-1"></div>
		<div class="col-lg-8 col-md-10 col-sm-12">
			<!-- content -->
			{% block content_2 %}
			{% endblock %}
		</div>
		<div class="col-lg-2 col-md-1"></div>
	</div>
</div>
<!-- <div class="col-lg-9 col-md-9" style="padding: 50px">{% block content_header %}{% endblock %}</div>
<div class="col-lg-3 col-md-3"></div>
-->
<!-- Footer -->
{% include 'footer.html' %}
<!-- Bootstrap core JavaScript -->
<script src="{% static 'base/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/collect_email.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
The doctor will see you now! | {{ block.super }}
{% endblock %}

{% block head_extras %}
{{ form.media }}
{% endblock %}


{% block content_1 %}

<!-- Icons Grid -->
<section class="features-icons bg-light text-center" style="padding-top: 0px;">
	<div class="container">
		<div class="row">
			<div class="col-xl-9 mx-auto">
				<img class="img-fluid mb-3" width="40%" src="{% static 'base/img/LogoMakr_5MpNGv.png' %}" alt="">
				<br><span style="font-size: 80px;">Insta<b class="text-primary">2Blog</b></span>
				<h1 class="mb-5">One click blog from your Instagram.</h1>
			</div>
		</div>
		<div class="row justify-content-md-center">
			<div class="col-lg-8">
				
				<h3>Oops...</h3>
				<p class="lead mb-0">Looks like you've caught us in development mode.</p>
				<p>I am working hard to bring Insta<b class="text-primary">2Blog</b> to life. Things are looking up for this us here, and we should be ready in a few days. If you'd like us to send you a remainder when Insta<b class="text-primary">2Blog</b> is ready, just put your email address below!</p>
				
			</div>
		</div>

	</div>
</section>


{% endblock %}

templates/error_404.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Error 404! Everything is under control, Please STAY CALM | {{ block.super }}
{% endblock %}

{% block head_extras %}
{{ form.media }}
{% endblock %}


{% block content_2 %}

<h1><span class="text-muted">Oops!</span>
</h1>

<h3>
    ERROR 404
</h3>
<h3><small>Page not found</small></h3>
<p>Looks like, What you are looking for... doesn't exist <sup>yet</sup>.</p>


<p>Insta2blog.com is still in beta and this might happen. I am working to fix it.</p>


<h3>Contact Me</h3>
<p>If you are seeing this quite often, please contact me:</p>
<ul>
    <li>By email: alikhundmiri.developer@gmail.com</li>
    <li>on Instagram: <a href="https://www.instagram.com/alicodermaker">Alicodermaker</a></li>
    <li>on Twitter: <a href="https://www.twitter.com/alicodermaker">Alicodermaker</a></li>

</ul>

{% endblock %}

templates/footer.html
<footer class="footer bg-light">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 h-100 text-center text-lg-left my-auto">
				<ul class="list-inline mb-2">
					<li class="list-inline-item">
						<a href="{% url 'newsletter:index' %}">Home</a>
					</li>
					<li class="list-inline-item">&sdot;</li>
					<li class="list-inline-item">
						<a target="_blank" href="https://docs.google.com/document/d/1vGQoJMWdFpbRb2sXR6riVrkgRs6AFD3L7cwHHdfB3k0/edit?usp=sharing">About</a>
					</li>
					<li class="list-inline-item">&sdot;</li>
					<li class="list-inline-item">
						<a href="{% url 'newsletter:features' %}">Features</a>
					</li>
					<li class="list-inline-item">&sdot;</li>
					<li class="list-inline-item">
						<a href="{% url 'newsletter:newsletter_signup' %}">Learn More</a>
					</li>
					<li class="list-inline-item">&sdot;</li>
					<li class="list-inline-item">
						<a href="{% url 'newsletter:paywall_test' %}">Pricing</a>
					</li>
				</ul>

				<ul class="list-inline mb-2">
					<li class="list-inline-item">
						<a href="{% url 'privacy_policy' %}">Privacy Policy</a>
					</li>
					<li class="list-inline-item">&sdot;</li>
					<li class="list-inline-item">
						<a href="{% url 'term_of_use' %}">Terms of Use</a>
					</li>
				</ul>
				<p class="text-muted small mb-4 mb-lg-0">&copy; AliCoderMaker // Ali Khundmiri 2018. All Rights Reserved.</p>
				<p class="text-muted small">Beta unstable Release.<br>Version 0.0.1</p>
			</div>
			<div class="col-lg-6 h-100 text-center text-lg-right my-auto">
				<ul class="list-inline mb-0">
					<li class="list-inline-item mr-3">
						<a href="https://www.facebook.com/alicodermaker">
							<i class="fab fa-facebook fa-2x fa-fw"></i>
						</a>
					</li>
					<li class="list-inline-item mr-3">
						<a href="https://www.twitter.com/alicodermaker">
							<i class="fab fa-twitter-square fa-2x fa-fw"></i>
						</a>
					</li>
					<li class="list-inline-item">
						<a href="https://www.instagram.com/alicodermaker">
							<i class="fab fa-instagram fa-2x fa-fw"></i>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</footer>

templates/general_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
{{top_text}} | {{ block.super }}
{% endblock %}

{% block header0 %}
{{ form.media }}
{% endblock %}

{% block content_2 %}
<div class="row">
	<div class="col">
		<h3>{{top_text}}</h3>
		<h3><small>{{form_text}}</small></h3>
	</div>
</div>
<div class="row">
	<div class="col">
		<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
			{{ form|crispy }}
			<input type='submit' class='btn btn-outline-primary btn-lg' value='{{ tab_text }}'/>
		</form>
	</div>
</div>

<!-- login via facebook -->
<a href="{% url 'accounts:facebook_login' %}">login via Facebook</a>

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Landing Page - Start Bootstrap Theme</title>

	<!-- Bootstrap core CSS -->
	<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

	<!-- Custom fonts for this template -->
	<link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
	<link href="vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

	<!-- Custom styles for this template -->
	<link href="css/landing-page.min.css" rel="stylesheet">

</head>

<body>

	<!-- Navigation -->
	<nav class="navbar navbar-light bg-light static-top">
		<div class="container">
			<a class="navbar-brand" href="#">Start Bootstrap</a>
			<a class="btn btn-primary" href="#">Sign In</a>
		</div>
	</nav>

	<!-- Masthead -->
	<header class="masthead text-white text-center">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-xl-9 mx-auto">
					<h1 class="mb-5">Build a landing page for your business or project and generate more leads!</h1>
				</div>
				<div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
					<form>
						<div class="form-row">
							<div class="col-12 col-md-9 mb-2 mb-md-0">
								<input type="email" class="form-control form-control-lg" placeholder="Enter your email...">
							</div>
							<div class="col-12 col-md-3">
								<button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</header>

	<!-- Icons Grid -->
	<section class="features-icons bg-light text-center">
		<div class="container">
			<div class="row">
				<div class="col-lg-4">
					<div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
						<div class="features-icons-icon d-flex">
							<i class="icon-screen-desktop m-auto text-primary"></i>
						</div>
						<h3>Fully Responsive</h3>
						<p class="lead mb-0">This theme will look great on any device, no matter the size!</p>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
						<div class="features-icons-icon d-flex">
							<i class="icon-layers m-auto text-primary"></i>
						</div>
						<h3>Bootstrap 4 Ready</h3>
						<p class="lead mb-0">Featuring the latest build of the new Bootstrap 4 framework!</p>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="features-icons-item mx-auto mb-0 mb-lg-3">
						<div class="features-icons-icon d-flex">
							<i class="icon-check m-auto text-primary"></i>
						</div>
						<h3>Easy to Use</h3>
						<p class="lead mb-0">Ready to use with your own content, or customize the source files!</p>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Image Showcases -->
	<section class="showcase">
		<div class="container-fluid p-0">
			<div class="row no-gutters">

				<div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-1.jpg');"></div>
				<div class="col-lg-6 order-lg-1 my-auto showcase-text">
					<h2>Fully Responsive Design</h2>
					<p class="lead mb-0">When you use a theme created by Start Bootstrap, you know that the theme will look great on any device, whether it's a phone, tablet, or desktop the page will behave responsively!</p>
				</div>
			</div>
			<div class="row no-gutters">
				<div class="col-lg-6 text-white showcase-img" style="background-image: url('img/bg-showcase-2.jpg');"></div>
				<div class="col-lg-6 my-auto showcase-text">
					<h2>Updated For Bootstrap 4</h2>
					<p class="lead mb-0">Newly improved, and full of great utility classes, Bootstrap 4 is leading the way in mobile responsive web development! All of the themes on Start Bootstrap are now using Bootstrap 4!</p>
				</div>
			</div>
			<div class="row no-gutters">
				<div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-3.jpg');"></div>
				<div class="col-lg-6 order-lg-1 my-auto showcase-text">
					<h2>Easy to Use &amp; Customize</h2>
					<p class="lead mb-0">Landing Page is just HTML and CSS with a splash of SCSS for users who demand some deeper customization options. Out of the box, just add your content and images, and your new landing page will be ready to go!</p>
				</div>
			</div>
		</div>
	</section>

	<!-- Testimonials -->
	<section class="testimonials text-center bg-light">
		<div class="container">
			<h2 class="mb-5">What people are saying...</h2>
			<div class="row">
				<div class="col-lg-4">
					<div class="testimonial-item mx-auto mb-5 mb-lg-0">
						<img class="img-fluid rounded-circle mb-3" src="img/testimonials-1.jpg" alt="">
						<h5>Margaret E.</h5>
						<p class="font-weight-light mb-0">"This is fantastic! Thanks so much guys!"</p>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="testimonial-item mx-auto mb-5 mb-lg-0">
						<img class="img-fluid rounded-circle mb-3" src="img/testimonials-2.jpg" alt="">
						<h5>Fred S.</h5>
						<p class="font-weight-light mb-0">"Bootstrap is amazing. I've been using it to create lots of super nice landing pages."</p>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="testimonial-item mx-auto mb-5 mb-lg-0">
						<img class="img-fluid rounded-circle mb-3" src="img/testimonials-3.jpg" alt="">
						<h5>Sarah	W.</h5>
						<p class="font-weight-light mb-0">"Thanks so much for making these free resources available to us!"</p>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Call to Action -->
	<section class="call-to-action text-white text-center">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-xl-9 mx-auto">
					<h2 class="mb-4">Ready to get started? Sign up now!</h2>
				</div>
				<div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
					<form>
						<div class="form-row">
							<div class="col-12 col-md-9 mb-2 mb-md-0">
								<input type="email" class="form-control form-control-lg" placeholder="Enter your email...">
							</div>
							<div class="col-12 col-md-3">
								<button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</section>

	<!-- Footer -->
	<footer class="footer bg-light">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 h-100 text-center text-lg-left my-auto">
					<ul class="list-inline mb-2">
						<li class="list-inline-item">
							<a href="#">About</a>
						</li>
						<li class="list-inline-item">&sdot;</li>
						<li class="list-inline-item">
							<a href="#">Contact</a>
						</li>
						<li class="list-inline-item">&sdot;</li>
						<li class="list-inline-item">
							<a href="#">Terms of Use</a>
						</li>
						<li class="list-inline-item">&sdot;</li>
						<li class="list-inline-item">
							<a href="#">Privacy Policy</a>
						</li>
					</ul>
					<p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2018. All Rights Reserved.</p>
				</div>
				<div class="col-lg-6 h-100 text-center text-lg-right my-auto">
					<ul class="list-inline mb-0">
						<li class="list-inline-item mr-3">
							<a href="#">
								<i class="fab fa-facebook fa-2x fa-fw"></i>
							</a>
						</li>
						<li class="list-inline-item mr-3">
							<a href="#">
								<i class="fab fa-twitter-square fa-2x fa-fw"></i>
							</a>
						</li>
						<li class="list-inline-item">
							<a href="#">
								<i class="fab fa-instagram fa-2x fa-fw"></i>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</footer>

	<!-- Bootstrap core JavaScript -->
	<script src="vendor/jquery/jquery.min.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="{% url 'newsletter:index' %}">Insta<b class="text-primary">2Blog</b><sup style="color: gray">MVP</sup></a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			{% if request.user.is_authenticated %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a>
			</li>
			<!-- <li class="nav-item">
				<a class="nav-link" href="{% url 'blog:blog_latest' request.user.username %}">latest</a>
			</li> -->
			{% endif %}

		</ul>
		<ul class="navbar-nav">
			{% if request.user.is_authenticated %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'logout' %}">logout</a>
			</li>
			{% else %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'register' %}">Signup</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'login' %}">Login</a>
			</li>
			{% endif %}
		</ul>

	</div>
</nav>

templates/term_of_use.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Thank you. I'll mail you soon! | {{ block.super }}
{% endblock %}

{% block head_extras %}
{{ form.media }}
{% endblock %}


{% block content_1 %}

<h1>Website Terms and Conditions of Use</h1>

<h2>1. Terms</h2>

<p>By accessing this Website, accessible from insta2blog.com, you are agreeing to be bound by these Website Terms and Conditions of Use and agree that you are responsible for the agreement with any applicable local laws. If you disagree with any of these terms, you are prohibited from accessing this site. The materials contained in this Website are protected by copyright and trade mark law. <a href="https://termsofservicegenerator.net">These Terms of Service</a> has been created with the help of the Terms of Service Generator.</p>

<h2>2. Use License</h2>

<p>Permission is granted to temporarily download one copy of the materials on insta2blog's Website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:</p>

<ul>
    <li>modify or copy the materials;</li>
    <li>use the materials for any commercial purpose or for any public display;</li>
    <li>attempt to reverse engineer any software contained on insta2blog's Website;</li>
    <li>remove any copyright or other proprietary notations from the materials; or</li>
    <li>transferring the materials to another person or "mirror" the materials on any other server.</li>
</ul>

<p>This will let insta2blog to terminate upon violations of any of these restrictions. Upon termination, your viewing right will also be terminated and you should destroy any downloaded materials in your possession whether it is printed or electronic format.</p>

<h2>3. Disclaimer</h2>

<p>All the materials on insta2blog’s Website are provided "as is". insta2blog makes no warranties, may it be expressed or implied, therefore negates all other warranties. Furthermore, insta2blog does not make any representations concerning the accuracy or reliability of the use of the materials on its Website or otherwise relating to such materials or any sites linked to this Website.</p>

<h2>4. Limitations</h2>

<p>insta2blog or its suppliers will not be hold accountable for any damages that will arise with the use or inability to use the materials on insta2blog’s Website, even if insta2blog or an authorize representative of this Website has been notified, orally or written, of the possibility of such damage. Some jurisdiction does not allow limitations on implied warranties or limitations of liability for incidental damages, these limitations may not apply to you.</p>

<h2>5. Revisions and Errata</h2>

<p>The materials appearing on insta2blog’s Website may include technical, typographical, or photographic errors. insta2blog will not promise that any of the materials in this Website are accurate, complete, or current. insta2blog may change the materials contained on its Website at any time without notice. insta2blog does not make any commitment to update the materials.</p>

<h2>6. Links</h2>

<p>insta2blog has not reviewed all of the sites linked to its Website and is not responsible for the contents of any such linked site. The presence of any link does not imply endorsement by insta2blog of the site. The use of any linked website is at the user’s own risk.</p>

<h2>7. Site Terms of Use Modifications</h2>

<p>insta2blog may revise these Terms of Use for its Website at any time without prior notice. By using this Website, you are agreeing to be bound by the current version of these Terms and Conditions of Use.</p>

<h2>8. Your Privacy</h2>

<p>Please read <a href="{% url 'privacy_policy' %}">our Privacy Policy</a>.</p>

<h2>9. Governing Law</h2>

<p>Any claim related to insta2blog's Website shall be governed by the laws of India-Telengana state without regards to its conflict of law provisions.</p>
{% endblock %}